###################################################################
# This is a makefile that builds the Irish Tokeniser
# Elaine Uí Dhonnchadha 
# February 2003
# FOMA 2012
# XFST 2013
###################################################################

# TOKENIZER

#tok-gael.fst:  tok-gael.fst
tok-gael.fst: xfst-tok-gael.script
	@echo
	@echo " <<< Tokeniser >>>"
	@echo
	@xfst -f xfst-tok-gael.script
#	@foma -f xfst-tok-gael.script

